"""
Sticker Pack Configuration — Chubby Mochi Penguin
===================================================
A round, squishy baby penguin with a dark blue-black back and white belly.
Painted illustration style with thick outlines and bold text overlays.

16 daily-expression stickers with per-sticker text + colour configuration.
Text is composited in post-processing (Pillow), NOT generated by SDXL.
"""

# =============================================================================
# CHARACTER DEFINITION
# =============================================================================
CHARACTER = {
    "name": "Mochi Penguin",
    "species": "round baby penguin",
    "body_color": "#2C3E6B",  # dark blue-black
    "blush_color": "#FF9999",  # soft pink
    "outline_color": "#333333",  # dark charcoal
    "eye_style": "large shiny black round eyes, expressive, with tiny white highlight dots",
    "accessory": None,
    "proportions": "chibi, extremely round body like a ball, tiny stubby legs, head is 55% of body height",
    # --- v2 fields for character-agnostic prompt building ---
    "body_description": (
        "cute round chubby baby penguin, dark blue-black back feathers, "
        "white belly patch, large shiny black round eyes, "
        "tiny highlight dots in eyes, small orange beak, "
        "extremely round ball-shaped body, "
        "tiny orange webbed feet, small stubby flippers, "
        "pink blush marks on cheeks"
    ),
    "features": [
        "round chubby body",
        "dark blue-black back feathers",
        "white belly patch",
        "small orange beak",
        "tiny orange webbed feet",
        "shiny black eyes with highlights",
        "small stubby flippers",
        "pink blush cheeks",
    ],
}

# =============================================================================
# ART STYLE  — painted illustration (matches benchmark)
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "thick black outlines, consistent 3-4px width",
    "coloring": "semi-realistic painting style, soft painterly shading, warm color palette",
    "background": "clean solid white background with no other elements",
    "extras": (
        "sticker illustration style, dynamic expressive poses, "
        "action effects like motion lines and sweat drops, "
        "kawaii aesthetic with exaggerated proportions"
    ),
}

# =============================================================================
# TEXT DEFAULTS — pack-level styling for Pillow text compositor
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 85,
    "outline_width": 6,
    "outline_color": "#1a1a1a",
    "shadow_offset": [4, 5],
    "shadow_color": "#00000099",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Chubby Mochi Penguin (16 stickers — daily expressions)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "chubby-mochi-penguin",
    "pack_name": "Chubby Mochi Penguin",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        # ------------------------------------------------------------------
        # 1 — Hello / Greeting
        # ------------------------------------------------------------------
        {
            "id": "01_hello",
            "emotion": "Hello / Greeting",
            "pose": "Standing facing forward, one flipper raised high waving enthusiastically",
            "props": "Bright cheerful smile, small motion lines near waving flipper",
            "emoji": "👋",
            "text": {"content": "HELLO!", "color": "#3399FF"},
        },
        # ------------------------------------------------------------------
        # 2 — Thank you
        # ------------------------------------------------------------------
        {
            "id": "02_thank_you",
            "emotion": "Thank You / Grateful",
            "pose": "Bowing forward at 45 degrees, both flippers pressed together",
            "props": "Peaceful closed eyes, sparkle effects around head",
            "emoji": "🙏",
            "text": {"content": "THANK YOU", "color": "#FF66AA"},
        },
        # ------------------------------------------------------------------
        # 3 — Sorry
        # ------------------------------------------------------------------
        {
            "id": "03_sorry",
            "emotion": "Sorry / Apologize",
            "pose": "Deep bow with body bent forward, looking up with guilty eyes",
            "props": "Large sweat drop on head, wavy guilt lines around body",
            "emoji": "🙇",
            "text": {"content": "SORRY", "color": "#6688BB"},
        },
        # ------------------------------------------------------------------
        # 4 — OK / Approval
        # ------------------------------------------------------------------
        {
            "id": "04_ok",
            "emotion": "OK / Approval",
            "pose": "Standing confidently, one flipper giving thumbs up gesture",
            "props": "Cheerful grin, sparkle near flipper tip",
            "emoji": "👍",
            "text": {"content": "OK!", "color": "#33BB55"},
        },
        # ------------------------------------------------------------------
        # 5 — What?! / Shocked
        # ------------------------------------------------------------------
        {
            "id": "05_what",
            "emotion": "Shocked / Confused",
            "pose": "Jumped back, flippers up near face in shock, beak wide open",
            "props": "Extremely wide eyes, question marks and exclamation marks around head",
            "emoji": "😱",
            "text": {"content": "WHAT?!", "color": "#3366FF"},
        },
        # ------------------------------------------------------------------
        # 6 — LOL / Laughing
        # ------------------------------------------------------------------
        {
            "id": "06_lol",
            "emotion": "Laughing hard",
            "pose": "Rolling on back laughing, flippers on belly, body shaking",
            "props": "Eyes squeezed shut, wide laughing beak, tears of joy, extra pink blush",
            "emoji": "😂",
            "text": {"content": "LOL", "color": "#FF3333"},
        },
        # ------------------------------------------------------------------
        # 7 — Love you
        # ------------------------------------------------------------------
        {
            "id": "07_love_you",
            "emotion": "Love / Affection",
            "pose": "Both flippers hugging a large pink heart against round body",
            "props": "Heart-shaped eyes, floating hearts above, extra pink blush",
            "emoji": "❤️",
            "text": {"content": "LOVE YOU!", "color": "#FF4488"},
        },
        # ------------------------------------------------------------------
        # 8 — Good night
        # ------------------------------------------------------------------
        {
            "id": "08_good_night",
            "emotion": "Sleepy / Good Night",
            "pose": "Curled up in a ball, eyes peacefully closed, tiny blanket pulled up",
            "props": "Three Zzz bubbles floating up, small crescent moon, stars above",
            "emoji": "🌙",
            "text": {"content": "GOOD NIGHT", "color": "#7766CC"},
        },
        # ------------------------------------------------------------------
        # 9 — Hungry
        # ------------------------------------------------------------------
        {
            "id": "09_hungry",
            "emotion": "Hungry / Starving",
            "pose": "Standing with flippers reaching forward, beak wide open",
            "props": "Drool drop from beak, sparkling eyes, tiny fish floating in thought bubble",
            "emoji": "🐟",
            "text": {"content": "HUNGRY", "color": "#FF8833"},
        },
        # ------------------------------------------------------------------
        # 10 — OMG / Surprised
        # ------------------------------------------------------------------
        {
            "id": "10_omg",
            "emotion": "Surprised / Amazed",
            "pose": "Both flippers pressed against cheeks, mouth in perfect O shape, leaning forward",
            "props": "Sparkling eyes, starburst effect behind, exclamation marks above head",
            "emoji": "😲",
            "text": {"content": "OMG!", "color": "#FF6699"},
        },
        # ------------------------------------------------------------------
        # 11 — Angry / Mad
        # ------------------------------------------------------------------
        {
            "id": "11_angry",
            "emotion": "Angry / Annoyed",
            "pose": "Standing with flippers on hips, puffed up body to look bigger, furrowed brows",
            "props": "Anger vein mark on forehead, steam coming from head, stomping foot lines",
            "emoji": "😤",
            "text": {"content": "HMPH!", "color": "#DD4444"},
        },
        # ------------------------------------------------------------------
        # 12 — Crying / Sad
        # ------------------------------------------------------------------
        {
            "id": "12_crying",
            "emotion": "Sad / Crying",
            "pose": "Sitting on ground, flippers covering eyes, body hunched over",
            "props": "Waterfall tears streaming down, rain cloud above head, wavy mouth",
            "emoji": "😢",
            "text": {"content": "SO SAD", "color": "#4477DD"},
        },
        # ------------------------------------------------------------------
        # 13 — Yay / Excited
        # ------------------------------------------------------------------
        {
            "id": "13_yay",
            "emotion": "Excited / Celebrating",
            "pose": "Jumping high with both flippers thrown up, huge open-mouth grin",
            "props": "Sparkle effects, confetti pieces, speed lines showing energy",
            "emoji": "🎉",
            "text": {"content": "YAY!", "color": "#FFCC00"},
        },
        # ------------------------------------------------------------------
        # 14 — Please / Begging
        # ------------------------------------------------------------------
        {
            "id": "14_please",
            "emotion": "Begging / Please",
            "pose": "Sitting with flippers pressed together, big round puppy eyes, slight head tilt",
            "props": "Sparkling watery eyes, tiny sweat drop, pouting beak",
            "emoji": "🥺",
            "text": {"content": "PLEASE", "color": "#CC77DD"},
        },
        # ------------------------------------------------------------------
        # 15 — Chillin / Relaxed
        # ------------------------------------------------------------------
        {
            "id": "15_chillin",
            "emotion": "Cool / Relaxing",
            "pose": "Lying back on a small ice block, one flipper behind head, relaxed half-closed eyes",
            "props": "Tiny sunglasses on head, cool sparkle effect, content smile",
            "emoji": "😎",
            "text": {"content": "CHILLIN'", "color": "#44BBCC"},
        },
        # ------------------------------------------------------------------
        # 16 — BRB / Sliding away
        # ------------------------------------------------------------------
        {
            "id": "16_brb",
            "emotion": "Bye / Be right back",
            "pose": "Belly-sliding away on ice, one flipper waving back, looking over shoulder",
            "props": "Speed lines behind body, ice spray particles, cheeky smile",
            "emoji": "🏃",
            "text": {"content": "BRB!", "color": "#55AADD"},
        },
    ],
    "platforms": [
        "whatsapp",
        "telegram",
        "line",
        "imessage_large",
    ],
}
