"""
Sticker Pack Configuration — generated by new-sticker-pack skill.
Edit CHARACTER, STYLE, and PACK_CONFIG to customise your pack.
"""

# =============================================================================
# CHARACTER DEFINITION
# =============================================================================
CHARACTER = {
    "name": "{{CHARACTER_NAME}}",
    "species": "{{CHARACTER_SPECIES}}",
    "body_color": "{{BODY_COLOR}}",
    "blush_color": "{{BLUSH_COLOR}}",
    "outline_color": "#333333",
    "eye_style": "{{EYE_STYLE}}",
    "accessory": "{{ACCESSORY}}",
    "proportions": "{{PROPORTIONS}}",
    "body_description": ("{{BODY_DESCRIPTION}}"),
    "features": [{{FEATURES_LIST}}],
}

# =============================================================================
# ART STYLE
# =============================================================================
STYLE = {
    "outline_type": "thick uniform outline, consistent 3-4px width",
    "coloring": "flat colors only, absolutely no gradients, no realistic shading",
    "background": "clean solid white background with no other elements",
    "extras": (
        "die-cut sticker style with a thick white outline border "
        "around the ENTIRE character"
    ),
    # Options: "flat_vector" | "painted_illustration"
    "art_style": "{{ART_STYLE}}",
}

# =============================================================================
# PACK CONFIGURATION
# =============================================================================
PACK_CONFIG = {
    "pack_id": "{{PACK_ID}}",
    "pack_name": "{{PACK_NAME}}",
    "publisher": "{{PUBLISHER}}",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": None,
    "platforms": {{PLATFORMS_LIST}},
    "stickers": [{{STICKERS_LIST}}],
}
