"""
Sticker Pack Configuration — generated by new-sticker-pack skill.
Fill every {{PLACEHOLDER}} with real values. Do NOT include telegram_animated
in the platforms list — animated TGS is generated via --telegram-animated flag.

Required character keys (all used by image_generator.py):
  name, species, body_color, blush_color, outline_color,
  eye_style, accessory, proportions

Required style keys (all used by image_generator.py):
  outline_type, coloring, background, extras, art_style
"""

PACK_CONFIG = {
    "pack_id": "{{PACK_ID}}",
    "pack_name": "{{PACK_NAME}}",
    "publisher": "{{PUBLISHER}}",
    "character": {
        # Required by image_generator.py — do not omit any key
        "name": "{{CHARACTER_NAME}}",
        "species": "{{CHARACTER_SPECIES}}",
        "body_color": "{{BODY_COLOR}}",  # e.g. "cream white"
        "blush_color": "{{BLUSH_COLOR}}",  # e.g. "soft pink"
        "outline_color": "{{OUTLINE_COLOR}}",  # e.g. "black" or "#333333"
        "eye_style": "{{EYE_STYLE}}",  # e.g. "large glossy black dot eyes"
        "accessory": "{{ACCESSORY}}",  # singular string, e.g. "small pink bow"
        "proportions": "{{PROPORTIONS}}",  # e.g. "chubby round body, stubby limbs"
    },
    "style": {
        # Required by image_generator.py — do not omit any key
        "outline_type": "thick uniform black outline, consistent 4px width",
        "coloring": "flat pastel colors, no gradients, no realistic shading",
        "background": "transparent background, no background elements",
        "extras": "die-cut sticker style with a thick white outline border around the ENTIRE character",
        "art_style": "{{ART_STYLE}}",  # e.g. "kawaii flat_vector illustration"
    },
    # Do NOT include "telegram_animated" here — it is handled via --telegram-animated flag
    "platforms": [
        "line",
        "telegram",
        "whatsapp",
        "imessage_large",
        "print_etsy",
    ],
    "stickers": [
        {
            "id": "01_happy",
            "emotion": "Happy",
            "pose": "{{POSE_01}}",
            "props": "{{PROPS_01}}",
            "emoji": "😊",
            "animation": {"type": "bounce", "duration_ms": 2000, "loop": True},
        },
        {
            "id": "02_love",
            "emotion": "In Love",
            "pose": "{{POSE_02}}",
            "props": "{{PROPS_02}}",
            "emoji": "❤️",
        },
        {
            "id": "03_sad",
            "emotion": "Sad",
            "pose": "{{POSE_03}}",
            "props": "{{PROPS_03}}",
            "emoji": "😢",
        },
        {
            "id": "04_angry",
            "emotion": "Angry",
            "pose": "{{POSE_04}}",
            "props": "{{PROPS_04}}",
            "emoji": "😠",
        },
        {
            "id": "05_sleepy",
            "emotion": "Sleepy",
            "pose": "{{POSE_05}}",
            "props": "{{PROPS_05}}",
            "emoji": "😴",
        },
        {
            "id": "06_surprised",
            "emotion": "Surprised",
            "pose": "{{POSE_06}}",
            "props": "{{PROPS_06}}",
            "emoji": "😲",
        },
        {
            "id": "07_laughing",
            "emotion": "Laughing",
            "pose": "{{POSE_07}}",
            "props": "{{PROPS_07}}",
            "emoji": "😂",
        },
        {
            "id": "08_thumbsup",
            "emotion": "Thumbs Up / Approval",
            "pose": "{{POSE_08}}",
            "props": "{{PROPS_08}}",
            "emoji": "👍",
        },
    ],
}
