"""
Sticker Pack Configuration — Chubby Mochi Hamster
==================================================
A round, squishy hamster with puffed cheeks and warm orange-brown fur.
Painted illustration style with thick outlines and bold text overlays.

14 stickers with per-sticker text + colour configuration.
Text is composited in post-processing (Pillow), NOT generated by SDXL.
"""

# =============================================================================
# CHARACTER DEFINITION
# =============================================================================
CHARACTER = {
    "name": "Mochi Hamster",
    "species": "round hamster",
    "body_color": "#E8A84C",  # warm orange-brown
    "blush_color": "#FF9999",  # soft pink
    "outline_color": "#333333",  # dark charcoal
    "eye_style": "large shiny black round eyes, expressive, with tiny white highlight dots",
    "accessory": None,
    "proportions": "chibi, extremely round body like a ball, tiny stubby legs, head is 55% of body height",
    # --- New v2 fields for character-agnostic prompt building ---
    "body_description": (
        "cute round chubby hamster, warm orange-brown fur, "
        "white belly patch, large shiny black round eyes, "
        "tiny highlight dots in eyes, small pink nose, "
        "large round ears, extremely round ball-shaped body, "
        "puffed cheek pouches, tiny stubby paws, "
        "pink blush marks on cheeks"
    ),
    "features": [
        "round chubby body",
        "warm orange-brown fur",
        "white belly patch",
        "puffed cheek pouches",
        "large round ears",
        "shiny black eyes with highlights",
        "tiny stubby paws",
        "pink blush cheeks",
    ],
}

# =============================================================================
# ART STYLE  — painted illustration (matches benchmark)
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "thick black outlines, consistent 3-4px width",
    "coloring": "semi-realistic painting style, soft painterly shading, warm color palette",
    "background": "clean solid white background with no other elements",
    "extras": (
        "sticker illustration style, dynamic expressive poses, "
        "action effects like motion lines and sweat drops, "
        "kawaii aesthetic with exaggerated proportions"
    ),
}

# =============================================================================
# TEXT DEFAULTS — pack-level styling for Pillow text compositor
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 85,
    "outline_width": 6,
    "outline_color": "#1a1a1a",
    "shadow_offset": [4, 5],
    "shadow_color": "#00000099",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Chubby Mochi Hamster (14 stickers)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "chubby-mochi-hamster",
    "pack_name": "Chubby Mochi Hamster",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        {
            "id": "01_hello",
            "emotion": "Hello / Greeting",
            "pose": "Standing facing forward, one paw raised high waving enthusiastically",
            "props": "Bright cheerful smile, small motion lines near waving paw",
            "emoji": "👋",
            "text": {"content": "HELLO!", "color": "#FF9900"},
        },
        {
            "id": "02_thank_you",
            "emotion": "Thank You / Grateful",
            "pose": "Bowing forward at 45 degrees, both paws pressed together",
            "props": "Peaceful closed eyes, sparkle effects around head",
            "emoji": "🙏",
            "text": {"content": "THANK YOU", "color": "#FF66AA"},
        },
        {
            "id": "03_sorry",
            "emotion": "Sorry / Apologize",
            "pose": "Deep bow with body bent forward, looking up with guilty eyes",
            "props": "Large sweat drop on head, wavy guilt lines around body",
            "emoji": "🙇",
            "text": {"content": "SORRY", "color": "#6688BB"},
        },
        {
            "id": "04_ok",
            "emotion": "OK / Approval",
            "pose": "Standing confidently, one paw giving thumbs up",
            "props": "Cheerful grin, sparkle near thumb",
            "emoji": "👍",
            "text": {"content": "OK!", "color": "#33BB55"},
        },
        {
            "id": "05_what",
            "emotion": "Shocked / Confused",
            "pose": "Jumped back, paws up near face in shock, mouth wide open",
            "props": "Extremely wide eyes, question marks and exclamation marks around head",
            "emoji": "😱",
            "text": {"content": "WHAT?!", "color": "#3366FF"},
        },
        {
            "id": "06_lol",
            "emotion": "Laughing hard",
            "pose": "Rolling on back laughing, paws on belly, body shaking",
            "props": "Eyes squeezed shut, wide laughing mouth, tears of joy, cheeks puffed even more",
            "emoji": "😂",
            "text": {"content": "LOL", "color": "#FF3333"},
        },
        {
            "id": "07_love_you",
            "emotion": "Love / Affection",
            "pose": "Both paws hugging a large pink heart against round body",
            "props": "Heart-shaped eyes, floating hearts above, extra pink blush",
            "emoji": "❤️",
            "text": {"content": "LOVE YOU!", "color": "#FF4488"},
        },
        {
            "id": "08_good_night",
            "emotion": "Sleepy / Good Night",
            "pose": "Curled up in a ball, eyes peacefully closed, tiny blanket pulled up",
            "props": "Three Zzz bubbles floating up, small crescent moon, stars above",
            "emoji": "🌙",
            "text": {"content": "GOOD NIGHT", "color": "#7766CC"},
        },
        {
            "id": "09_hungry",
            "emotion": "Hungry / Starving",
            "pose": "Standing with paws reaching forward, mouth wide open drooling",
            "props": "Drool drop from mouth, sparkling eyes, cheek pouches deflated (empty)",
            "emoji": "🤤",
            "text": {"content": "HUNGRY", "color": "#FF8833"},
        },
        {
            "id": "10_busy",
            "emotion": "Busy / Working",
            "pose": "Sitting at tiny laptop, paws typing rapidly, focused squinting eyes",
            "props": "Sweat drop on temple, speed lines near typing paws, determined expression",
            "emoji": "💻",
            "text": {"content": "BUSY", "color": "#5599CC"},
        },
        {
            "id": "11_waiting",
            "emotion": "Waiting / Impatient",
            "pose": "Standing with arms crossed, tapping one foot, looking at invisible watch",
            "props": "Half-lidded unamused eyes, small clock icon, tap-tap motion lines near foot",
            "emoji": "⏰",
            "text": {"content": "WAITING...", "color": "#AAAA44"},
        },
        {
            "id": "12_nooo",
            "emotion": "Despair / Nooo",
            "pose": "On knees, paws reaching up dramatically, head tilted back wailing",
            "props": "Waterfall tears from both eyes, dramatic background lines, mouth wide open",
            "emoji": "😭",
            "text": {"content": "NOOO!", "color": "#4477DD"},
        },
        {
            "id": "13_yes",
            "emotion": "Excited agreement / Yesss",
            "pose": "Jumping with both paws pumping in the air, huge grin",
            "props": "Sparkle effects, confetti pieces, speed lines showing energy",
            "emoji": "🎉",
            "text": {"content": "YES!", "color": "#FFCC00"},
        },
        {
            "id": "14_please",
            "emotion": "Begging / Please",
            "pose": "Sitting with paws pressed together in prayer position, big round puppy eyes",
            "props": "Sparkling watery eyes, slight head tilt, tiny sweat drop",
            "emoji": "🥺",
            "text": {"content": "PLEASE", "color": "#CC77DD"},
        },
    ],
    "platforms": [
        "whatsapp",
        "telegram",
        "line",
        "imessage_large",
    ],
}
