"""
Sticker Pack Configuration — Chubby Mochi Cat
==============================================
A round, squishy mochi-style cat with bold text overlays.
Painted illustration style with thick outlines and expressive poses.

10 stickers with per-sticker text + colour configuration.
Text is composited in post-processing (Pillow), NOT generated by SDXL.
"""

# =============================================================================
# CHARACTER DEFINITION
# =============================================================================
CHARACTER = {
    "name": "Mochi Cat",
    "species": "round cat",
    "body_color": "#FFB6C1",  # light pink
    "blush_color": "#FF69B4",  # hot pink
    "outline_color": "#333333",  # dark charcoal
    "eye_style": "large black oval eyes, no pupils, highly expressive",
    "accessory": None,
    "proportions": "chibi, very round body, head is 60% of total body height, stubby short limbs",
    # --- New v2 fields for character-agnostic prompt building ---
    "body_description": (
        "cute round chubby mochi cat, soft pink body, "
        "large expressive black oval eyes, no pupils, "
        "tiny pink nose, small rounded ears, "
        "very round potato-shaped body, stubby short limbs, "
        "pink blush marks on cheeks"
    ),
    "features": [
        "round chubby body",
        "pink fur",
        "black oval eyes",
        "tiny pink nose",
        "small rounded ears",
        "stubby paws",
        "pink blush cheeks",
    ],
}

# =============================================================================
# ART STYLE  — painted illustration (matches benchmark)
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "thick black outlines, consistent 3-4px width",
    "coloring": "semi-realistic painting style, soft painterly shading, warm color palette",
    "background": "clean solid white background with no other elements",
    "extras": (
        "sticker illustration style, dynamic expressive poses, "
        "action effects like motion lines and sweat drops, "
        "kawaii aesthetic with exaggerated proportions"
    ),
}

# =============================================================================
# TEXT DEFAULTS — pack-level styling for Pillow text compositor
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 90,
    "outline_width": 6,
    "outline_color": "#1a1a1a",
    "shadow_offset": [4, 5],
    "shadow_color": "#00000099",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Chubby Mochi Cat (10 stickers)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "chubby-mochi-cat",
    "pack_name": "Chubby Mochi Cat",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        {
            "id": "01_what",
            "emotion": "Shocked / Surprised",
            "pose": "Jumped back, paws up near face in shock, wide open mouth",
            "props": "Extremely wide circular eyes, exclamation marks around head, motion lines",
            "emoji": "😱",
            "text": {"content": "WHAT?!", "color": "#3366FF"},
        },
        {
            "id": "02_lol",
            "emotion": "Laughing hard",
            "pose": "Leaning back, one paw on belly, body shaking with laughter",
            "props": "Eyes squeezed shut happily, wide open laughing mouth, tears of joy",
            "emoji": "😂",
            "text": {"content": "LOL", "color": "#FF3333"},
        },
        {
            "id": "03_ok",
            "emotion": "OK / Approval",
            "pose": "Standing confidently, one paw giving thumbs up",
            "props": "Cheerful grin, sparkle near thumb, slight confident lean",
            "emoji": "👍",
            "text": {"content": "OK", "color": "#33BB55"},
        },
        {
            "id": "04_nope",
            "emotion": "Refusal / Rejection",
            "pose": "Both paws crossed in X shape in front of body, head turned away",
            "props": "Flat unamused expression, slight head shake motion lines",
            "emoji": "🙅",
            "text": {"content": "NOPE", "color": "#FF6633"},
        },
        {
            "id": "05_bye",
            "emotion": "Goodbye",
            "pose": "Walking away to the right, looking back over shoulder, one paw waving",
            "props": "Gentle smile, small motion lines near feet",
            "emoji": "👋",
            "text": {"content": "BYE", "color": "#9966CC"},
        },
        {
            "id": "06_lets_go",
            "emotion": "Excited / Pumped up",
            "pose": "Jumping with both paws pumping in the air, feet off ground",
            "props": "Star-shaped sparkles, determined bright eyes, speed lines radiating outward",
            "emoji": "🔥",
            "text": {"content": "LET'S GO", "color": "#FF9900"},
        },
        {
            "id": "07_im_done",
            "emotion": "Exhausted / Done with life",
            "pose": "Lying flat face-down on the ground, limbs splayed out",
            "props": "Dark eye bags, soul leaving body effect, small sweat drop",
            "emoji": "😵",
            "text": {"content": "I'M DONE", "color": "#6688AA"},
        },
        {
            "id": "08_perfect",
            "emotion": "Delighted / Chef's kiss",
            "pose": "Standing on tip-toes, both paws together near cheek, sparkling eyes",
            "props": "Heart eyes, sparkle effects around head, small floating hearts",
            "emoji": "🤩",
            "text": {"content": "PERFECT", "color": "#FF66AA"},
        },
        {
            "id": "09_sure",
            "emotion": "Casual agreement",
            "pose": "Standing relaxed with one paw raised in a casual wave, slight shrug",
            "props": "Half-lidded chill eyes, small smile, relaxed posture",
            "emoji": "😌",
            "text": {"content": "SURE", "color": "#55AADD"},
        },
        {
            "id": "10_yesss",
            "emotion": "Triumphant / Victory",
            "pose": "Jumping high with both paws raised in fist pump, legs spread in star jump",
            "props": "Wide triumphant grin, confetti pieces, sparkle effects, motion lines",
            "emoji": "🎉",
            "text": {"content": "YESSS!", "color": "#FFCC00"},
        },
    ],
    "platforms": [
        "whatsapp",
        "telegram",
        "line",
        "imessage_large",
    ],
}
