"""Pack configuration for Chubby Couple Mochi Hamster sticker pack."""

PACK_CONFIG = {
    "pack_id": "chubby-couple-mochi-hamster",
    "pack_name": "Chubby Couple Mochi Hamster",
    "publisher": "StickerFramework",
    "character": {
        "name": "Mochi Pair",
        "species": "hamsters",
        "body_color": "cream white with soft pink blush",
        "eye_style": "large glossy black dot eyes",
        "accessories": "one hamster wears a small pink bow, the other wears a tiny blue bowtie",
        "proportions": "extra chubby, mochi-round bodies, tiny stubby limbs, large heads",
        "notes": "Always shown as a couple — two hamsters together in each sticker",
    },
    "style": {
        "outline_type": "thick black outline",
        "coloring": "flat pastel colors with soft shadow",
        "background": "transparent",
        "art_style": "flat_vector kawaii",
    },
    "platforms": [
        "line",
        "telegram",
        "whatsapp",
        "telegram_animated",
        "imessage_large",
        "print_etsy",
    ],
    "stickers": [
        {
            "id": "01_happy",
            "emotion": "Happy",
            "pose": "Both hamsters jumping together with arms raised, feet off the ground",
            "props": "Small sparkle effects (4-pointed stars) around both heads",
            "emoji": "😊",
            "animation": {"type": "bounce", "duration_ms": 2000, "loop": True},
        },
        {
            "id": "02_love",
            "emotion": "In Love",
            "pose": "The two hamsters holding a large pink heart together between them, eyes closed blissfully",
            "props": "Small floating hearts above both heads",
            "emoji": "❤️",
        },
        {
            "id": "03_sad",
            "emotion": "Sad",
            "pose": "Both hamsters sitting hunched side by side, heads down",
            "props": "Single large blue teardrop on each cheek, small shared rain cloud above",
            "emoji": "😢",
        },
        {
            "id": "04_angry",
            "emotion": "Angry",
            "pose": "Both hamsters standing with fists clenched, leaning forward aggressively at each other",
            "props": "Puffed red cheeks, steam lines rising from their heads, anger vein on forehead",
            "emoji": "😠",
        },
        {
            "id": "05_sleepy",
            "emotion": "Sleepy",
            "pose": "Both hamsters curled up together in a ball, eyes half-closed",
            "props": "Three Zzz bubbles floating up, small shared pillow underneath",
            "emoji": "😴",
        },
        {
            "id": "06_surprised",
            "emotion": "Surprised",
            "pose": "Both hamsters jumped back slightly, paws up near faces in shock",
            "props": "Extremely wide circular eyes, tiny O-shaped mouths, exclamation marks above heads",
            "emoji": "😲",
        },
        {
            "id": "07_laughing",
            "emotion": "Laughing",
            "pose": "Both hamsters leaning back, paws on bellies",
            "props": "Eyes squeezed shut happily, wide open mouths, tear of joy on one eye each",
            "emoji": "😂",
        },
        {
            "id": "08_thumbsup",
            "emotion": "Thumbs Up / Approval",
            "pose": "Both hamsters standing upright, each giving a confident thumbs up to each other",
            "props": "Small sparkles near thumbs, confident smiles",
            "emoji": "👍",
        },
    ],
}
