"""
Sticker Pack Configuration — Jesus Christ 2
=============================================
A cute, chibi Jesus character with more daily messages of grace and hope.
Same character design as Jesus Christ 1, different emotions and messages.

16 stickers with per-sticker text + colour configuration.
Text is composited in post-processing (Pillow), NOT generated by DALL-E.
"""

# =============================================================================
# CHARACTER DEFINITION (same as jesus-christ-1 for consistency)
# =============================================================================
CHARACTER = {
    "name": "Jesus",
    "species": "human",
    "body_color": "#F5DEB3",
    "blush_color": "#FFB6C1",
    "outline_color": "#4A3728",
    "eye_style": "large, warm black oval eyes with gentle expression, no pupils, very expressive",
    "accessory": "simple white robe with light blue sash, small beard, shoulder-length brown hair",
    "proportions": "chibi, round face is 50% of body height, small hands, oversized head, cute stubby body",
    "body_description": (
        "cute chibi Jesus character, warm wheat skin, "
        "large gentle black oval eyes, small warm smile, "
        "short brown beard, shoulder-length wavy brown hair, "
        "simple flowing white robe with light blue sash, "
        "round chibi proportions, oversized head, stubby limbs, "
        "pink blush marks on cheeks, peaceful loving expression"
    ),
    "features": [
        "chibi proportions",
        "warm wheat skin",
        "gentle black oval eyes",
        "short brown beard",
        "wavy brown hair",
        "white robe with blue sash",
        "pink blush cheeks",
        "peaceful expression",
    ],
}

# =============================================================================
# ART STYLE
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "thick warm brown outlines, consistent 3-4px width",
    "coloring": "warm pastel colors, soft watercolor-like shading, gentle light source from above",
    "background": "clean solid white background with no other elements",
    "extras": (
        "kawaii sticker illustration style, gentle peaceful poses, "
        "soft glow effects and small sparkles, "
        "warm comforting aesthetic with round soft shapes"
    ),
}

# =============================================================================
# TEXT DEFAULTS
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 80,
    "outline_width": 6,
    "outline_color": "#3A2A1A",
    "shadow_offset": [4, 5],
    "shadow_color": "#00000066",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Jesus Christ 2 (16 stickers)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "jesus-christ-2",
    "pack_name": "Jesus Christ 2",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        {
            "id": "01_walk_by_faith",
            "emotion": "Determined / Faithful",
            "pose": "Walking forward confidently, one foot ahead, looking forward with purpose",
            "props": "Soft path of light under feet, sparkles trailing behind, hopeful gaze",
            "emoji": "🚶",
            "text": {"content": "WALK BY\nFAITH", "color": "#4682B4"},
        },
        {
            "id": "02_keep_praying",
            "emotion": "Persistent / Devoted",
            "pose": "Kneeling with hands clasped in prayer, head slightly bowed",
            "props": "Small light rays descending, peaceful aura, gentle devotion",
            "emoji": "🙏",
            "text": {"content": "KEEP\nPRAYING", "color": "#6A5ACD"},
        },
        {
            "id": "03_faith_over_fear",
            "emotion": "Brave / Courageous",
            "pose": "Standing tall with one fist raised, determined brave expression",
            "props": "Shield of light in other hand, bold golden sparkles, heroic pose",
            "emoji": "🛡️",
            "text": {"content": "FAITH OVER\nFEAR", "color": "#B22222"},
        },
        {
            "id": "04_his_grace",
            "emotion": "Serene / Grateful",
            "pose": "Arms outstretched to the sides, head tilted up, eyes closed peacefully",
            "props": "Soft rainfall of light particles, warm golden aura, transcendent peace",
            "emoji": "✨",
            "text": {"content": "HIS GRACE\nIS ENOUGH", "color": "#DAA520"},
        },
        {
            "id": "05_seek_him_first",
            "emotion": "Focused / Searching",
            "pose": "Hand shielding eyes like looking into distance, other hand on heart",
            "props": "Soft beam of light in the direction of gaze, hopeful expression",
            "emoji": "🔍",
            "text": {"content": "SEEK HIM\nFIRST", "color": "#2E8B57"},
        },
        {
            "id": "06_god_is_with_you",
            "emotion": "Comforting / Reassuring",
            "pose": "One arm extended as if placing hand on viewer's shoulder, warm smile",
            "props": "Soft warm glow around extended hand, gentle reassuring expression",
            "emoji": "🤗",
            "text": {"content": "GOD IS\nWITH YOU", "color": "#CD853F"},
        },
        {
            "id": "07_hope_in_him",
            "emotion": "Hopeful / Optimistic",
            "pose": "Looking upward with hands cupped together, holding a soft light",
            "props": "Small glowing orb in cupped hands, starry sparkles, hopeful eyes",
            "emoji": "🌟",
            "text": {"content": "HOPE\nIN HIM", "color": "#4169E1"},
        },
        {
            "id": "08_give_it_to_god",
            "emotion": "Surrendering / Trusting",
            "pose": "Hands open and releasing something upward, relaxed peaceful posture",
            "props": "Small butterflies or light particles floating upward, weight lifted feeling",
            "emoji": "🦋",
            "text": {"content": "GIVE IT\nTO GOD", "color": "#8B668B"},
        },
        {
            "id": "09_joy_of_the_lord",
            "emotion": "Ecstatic / Dancing",
            "pose": "Dancing joyfully with arms swaying, one foot kicked up, huge smile",
            "props": "Musical notes, sparkle effects, rainbow-tinted light particles, pure joy",
            "emoji": "💃",
            "text": {"content": "JOY OF\nTHE LORD", "color": "#FF6347"},
        },
        {
            "id": "10_be_kind",
            "emotion": "Gentle / Kind",
            "pose": "Kneeling to pick a flower, one hand gently cradling it, soft smile",
            "props": "Small flower, heart-shaped petals, gentle nature vibes",
            "emoji": "🌸",
            "text": {"content": "BE KIND", "color": "#DB7093"},
        },
        {
            "id": "11_forgive",
            "emotion": "Compassionate / Forgiving",
            "pose": "Both hands open in front of body palms up, soft understanding expression",
            "props": "Broken chain links fading away, soft healing light, peaceful aura",
            "emoji": "💜",
            "text": {"content": "FORGIVE", "color": "#9370DB"},
        },
        {
            "id": "12_you_matter",
            "emotion": "Affirming / Validating",
            "pose": "Pointing at viewer with warm smile, other hand making a heart shape",
            "props": "Small heart near pointing hand, warm encouraging glow, sparkles",
            "emoji": "💖",
            "text": {"content": "YOU\nMATTER", "color": "#E75480"},
        },
        {
            "id": "13_never_give_up",
            "emotion": "Motivating / Persistent",
            "pose": "Running forward with determined expression, one arm pumping",
            "props": "Speed lines, finish-line light ahead, determined focused eyes",
            "emoji": "🏃",
            "text": {"content": "NEVER\nGIVE UP", "color": "#FF8C00"},
        },
        {
            "id": "14_let_go_let_god",
            "emotion": "Surrendered / Peaceful",
            "pose": "Floating peacefully with arms spread wide, eyes closed, serene expression",
            "props": "Clouds beneath, soft angelic glow, weightless peaceful feeling",
            "emoji": "☁️",
            "text": {"content": "LET GO\nLET GOD", "color": "#87CEEB"},
        },
        {
            "id": "15_be_the_light",
            "emotion": "Inspiring / Radiant",
            "pose": "Standing with one hand holding a glowing lantern, warm inviting smile",
            "props": "Warm lantern glow illuminating face, soft light particles, guiding light",
            "emoji": "🕯️",
            "text": {"content": "BE THE\nLIGHT", "color": "#FFD700"},
        },
        {
            "id": "16_god_has_a_plan",
            "emotion": "Wise / Reassuring",
            "pose": "Sitting on a hill overlooking a sunset, looking into the distance with hope",
            "props": "Beautiful sunset colors, winding path visible below, peaceful contemplation",
            "emoji": "🗺️",
            "text": {"content": "GOD HAS\nA PLAN", "color": "#8B7355"},
        },
    ],
    "platforms": [
        "whatsapp",
        "telegram",
        "imessage_large",
        "print_etsy",
    ],
}
