"""
Sticker Pack Configuration — Jesus Christ 1
=============================================
A cute, chibi Jesus character with daily encouragement messages.
Warm pastel illustration style with thick outlines.

16 stickers with per-sticker text + colour configuration.
Text is composited in post-processing (Pillow), NOT generated by DALL-E.
"""

# =============================================================================
# CHARACTER DEFINITION
# =============================================================================
CHARACTER = {
    "name": "Jesus",
    "species": "human",
    "body_color": "#F5DEB3",  # warm wheat skin tone
    "blush_color": "#FFB6C1",  # light pink
    "outline_color": "#4A3728",  # warm dark brown
    "eye_style": "large, warm black oval eyes with gentle expression, no pupils, very expressive",
    "accessory": "simple white robe with light blue sash, small beard, shoulder-length brown hair",
    "proportions": "chibi, round face is 50% of body height, small hands, oversized head, cute stubby body",
    "body_description": (
        "cute chibi Jesus character, warm wheat skin, "
        "large gentle black oval eyes, small warm smile, "
        "short brown beard, shoulder-length wavy brown hair, "
        "simple flowing white robe with light blue sash, "
        "round chibi proportions, oversized head, stubby limbs, "
        "pink blush marks on cheeks, peaceful loving expression"
    ),
    "features": [
        "chibi proportions",
        "warm wheat skin",
        "gentle black oval eyes",
        "short brown beard",
        "wavy brown hair",
        "white robe with blue sash",
        "pink blush cheeks",
        "peaceful expression",
    ],
}

# =============================================================================
# ART STYLE — warm pastel illustration
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "thick warm brown outlines, consistent 3-4px width",
    "coloring": "warm pastel colors, soft watercolor-like shading, gentle light source from above",
    "background": "clean solid white background with no other elements",
    "extras": (
        "kawaii sticker illustration style, gentle peaceful poses, "
        "soft glow effects and small sparkles, "
        "warm comforting aesthetic with round soft shapes"
    ),
}

# =============================================================================
# TEXT DEFAULTS
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 80,
    "outline_width": 6,
    "outline_color": "#3A2A1A",
    "shadow_offset": [4, 5],
    "shadow_color": "#00000066",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Jesus Christ 1 (16 stickers)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "jesus-christ-1",
    "pack_name": "Jesus Christ 1",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        {
            "id": "01_god_bless_you",
            "emotion": "Loving / Blessing",
            "pose": "Both hands raised gently outward, palms facing forward in a blessing gesture",
            "props": "Soft golden glow around hands, small sparkles, peaceful closed-eye smile",
            "emoji": "🙏",
            "text": {"content": "GOD BLESS\nYOU", "color": "#DAA520"},
        },
        {
            "id": "02_praying_for_you",
            "emotion": "Compassionate / Prayerful",
            "pose": "Hands clasped together in prayer, head slightly bowed, eyes closed",
            "props": "Small rays of light above, serene peaceful expression, soft glow",
            "emoji": "🙏",
            "text": {"content": "PRAYING\nFOR YOU", "color": "#6A5ACD"},
        },
        {
            "id": "03_have_faith",
            "emotion": "Encouraging / Uplifting",
            "pose": "One hand on heart, the other reaching out warmly, confident gentle smile",
            "props": "Small heart near chest, warm sparkle effects, determined kind eyes",
            "emoji": "✨",
            "text": {"content": "HAVE FAITH", "color": "#4682B4"},
        },
        {
            "id": "04_god_is_good",
            "emotion": "Joyful / Celebratory",
            "pose": "Jumping with both fists raised in celebration, wide happy grin",
            "props": "Star sparkles, confetti-like light particles, joyful radiating energy",
            "emoji": "🌟",
            "text": {"content": "GOD IS\nGOOD", "color": "#FF8C00"},
        },
        {
            "id": "05_amen",
            "emotion": "Reverent / Agreement",
            "pose": "Hands clasped, gentle nod, serene closed-eye expression",
            "props": "Soft halo of light, tiny cross detail on robe, peaceful aura",
            "emoji": "🕊️",
            "text": {"content": "AMEN", "color": "#8B6914"},
        },
        {
            "id": "06_thank_you_lord",
            "emotion": "Grateful / Thankful",
            "pose": "Looking upward with both hands raised in gratitude, beaming smile",
            "props": "Rays of warm light from above, small golden sparkles, tears of joy",
            "emoji": "💛",
            "text": {"content": "THANK YOU\nLORD", "color": "#CD853F"},
        },
        {
            "id": "07_i_love_you",
            "emotion": "Loving / Affectionate",
            "pose": "Both arms forming a heart shape above head, warm gentle smile",
            "props": "Pink and red hearts floating around, warm rosy cheeks, soft pink glow",
            "emoji": "❤️",
            "text": {"content": "I LOVE\nYOU", "color": "#DC143C"},
        },
        {
            "id": "08_trust_in_him",
            "emotion": "Reassuring / Comforting",
            "pose": "Sitting calmly on a rock, one hand on heart, gentle warm smile",
            "props": "Soft warm glow around body, small floating hearts, calm serene vibe",
            "emoji": "💙",
            "text": {"content": "TRUST\nIN HIM", "color": "#4169E1"},
        },
        {
            "id": "09_you_are_blessed",
            "emotion": "Affirming / Warm",
            "pose": "Pointing gently at viewer with one hand, other hand over heart",
            "props": "Warm golden sparkle near pointing hand, loving expression",
            "emoji": "🌈",
            "text": {"content": "YOU ARE\nBLESSED", "color": "#E75480"},
        },
        {
            "id": "10_peace_be_with_you",
            "emotion": "Calm / Peaceful",
            "pose": "Standing with arms open wide in welcoming gesture, serene expression",
            "props": "Dove silhouette near shoulder, olive branch, soft halo glow",
            "emoji": "☮️",
            "text": {"content": "PEACE BE\nWITH YOU", "color": "#3CB371"},
        },
        {
            "id": "11_be_strong",
            "emotion": "Determined / Encouraging",
            "pose": "Flexing one arm gently, other hand giving thumbs up, bright smile",
            "props": "Small star near flexed arm, sparkle effects, confident posture",
            "emoji": "💪",
            "text": {"content": "BE STRONG", "color": "#B22222"},
        },
        {
            "id": "12_dont_worry",
            "emotion": "Soothing / Calming",
            "pose": "Waving both hands gently in a calming motion, soft reassuring smile",
            "props": "Soft pastel swirls, gentle calming aura, relaxed shoulders",
            "emoji": "😌",
            "text": {"content": "DON'T\nWORRY", "color": "#5F9EA0"},
        },
        {
            "id": "13_good_morning",
            "emotion": "Cheerful / Fresh",
            "pose": "Waving hello with one hand, other hand holding a small sun, bright smile",
            "props": "Sunrise rays, small birds, fresh morning sparkles",
            "emoji": "🌅",
            "text": {"content": "GOOD\nMORNING", "color": "#FFA500"},
        },
        {
            "id": "14_good_night",
            "emotion": "Gentle / Sleepy",
            "pose": "Eyes half-closed, one hand waving softly, slight sleepy tilt of head",
            "props": "Crescent moon, tiny stars, soft blue-purple night glow, zzz",
            "emoji": "🌙",
            "text": {"content": "GOOD\nNIGHT", "color": "#483D8B"},
        },
        {
            "id": "15_hallelujah",
            "emotion": "Ecstatic / Praising",
            "pose": "Both arms raised high to the sky, head tilted back, wide ecstatic grin",
            "props": "Bright light beams from above, musical notes, joyful energy radiating",
            "emoji": "🎶",
            "text": {"content": "HALLELUJAH", "color": "#B8860B"},
        },
        {
            "id": "16_stay_blessed",
            "emotion": "Warm / Farewell blessing",
            "pose": "One hand raised in gentle wave, other hand on heart, kind warm smile",
            "props": "Soft golden sparkles trailing from waving hand, gentle warm glow",
            "emoji": "✝️",
            "text": {"content": "STAY\nBLESSED", "color": "#8B7355"},
        },
    ],
    "platforms": [
        "whatsapp",
        "telegram",
        "imessage_large",
        "print_etsy",
    ],
}
