"""
Sticker Pack Configuration — Chubby Mochi Panda
================================================
A round, squishy panda with big sparkling eyes and rosy cheeks.
Painted illustration style with thick outlines and bold text overlays.

16 stickers with per-sticker text + colour configuration.
Text is composited in post-processing (Pillow), NOT generated by SDXL.
"""

# =============================================================================
# CHARACTER DEFINITION
# =============================================================================
CHARACTER = {
    "name": "Mochi Panda",
    "species": "round panda",
    "body_color": "#FFFFFF",  # classic white
    "blush_color": "#FFB3B3",  # soft rosy pink
    "outline_color": "#222222",  # near-black
    "eye_style": "large shiny black round eyes, expressive, with big white highlight dots",
    "accessory": "tiny bamboo leaf on head",
    "proportions": "chibi, extremely round body like a ball, tiny stubby legs, head is 55% of body height",
    # --- v2 fields for character-agnostic prompt building ---
    "body_description": (
        "cute round chubby panda, classic black and white fur, "
        "black eye patches shaped like ovals, large shiny black round eyes, "
        "big highlight dots in eyes, small round black nose, "
        "round ears with black fur, extremely round ball-shaped body, "
        "white fluffy belly, tiny stubby black paws, "
        "pink blush marks on cheeks, tiny bamboo leaf on head"
    ),
    "features": [
        "round chubby body",
        "classic black and white panda fur",
        "black oval eye patches",
        "round black ears",
        "shiny black eyes with big highlights",
        "tiny stubby black paws",
        "pink blush cheeks",
        "white fluffy belly",
        "tiny bamboo leaf on head",
    ],
}

# =============================================================================
# ART STYLE — painted illustration
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "thick black outlines, consistent 3-4px width",
    "coloring": "semi-realistic painting style, soft painterly shading, warm color palette",
    "background": "clean solid white background with no other elements",
    "extras": (
        "sticker illustration style, dynamic expressive poses, "
        "action effects like motion lines and sweat drops, "
        "kawaii aesthetic with exaggerated proportions"
    ),
}

# =============================================================================
# TEXT DEFAULTS — pack-level styling for Pillow text compositor
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 85,
    "outline_width": 6,
    "outline_color": "#1a1a1a",
    "shadow_offset": [4, 5],
    "shadow_color": "#00000099",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Chubby Mochi Panda (16 stickers)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "chubby-mochi-panda",
    "pack_name": "Chubby Mochi Panda",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        {
            "id": "01_hello",
            "emotion": "Hello / Greeting",
            "pose": "Standing facing forward, one paw raised high waving enthusiastically",
            "props": "Bright cheerful smile, small motion lines near waving paw",
            "emoji": "👋",
            "text": {"content": "HI!", "color": "#33BB55"},
        },
        {
            "id": "02_thank_you",
            "emotion": "Thank You / Grateful",
            "pose": "Bowing forward at 45 degrees, both paws pressed together",
            "props": "Peaceful closed eyes, sparkle effects around head",
            "emoji": "🙏",
            "text": {"content": "THANKS!", "color": "#FF66AA"},
        },
        {
            "id": "03_love",
            "emotion": "Love / Affection",
            "pose": "Both paws hugging a large pink heart against round body",
            "props": "Heart-shaped eyes, floating hearts above, extra pink blush",
            "emoji": "❤️",
            "text": {"content": "LOVE YOU", "color": "#FF4488"},
        },
        {
            "id": "04_lol",
            "emotion": "Laughing hard",
            "pose": "Rolling on back laughing, paws on belly, body shaking",
            "props": "Eyes squeezed shut, wide laughing mouth, tears of joy",
            "emoji": "😂",
            "text": {"content": "LOL", "color": "#FF3333"},
        },
        {
            "id": "05_ok",
            "emotion": "OK / Approval",
            "pose": "Standing confidently, one paw giving thumbs up",
            "props": "Cheerful grin, sparkle near thumb",
            "emoji": "👍",
            "text": {"content": "OK!", "color": "#33AA55"},
        },
        {
            "id": "06_what",
            "emotion": "Shocked / Confused",
            "pose": "Jumped back, paws up near face in shock, mouth wide open",
            "props": "Extremely wide eyes, question marks and exclamation marks around head",
            "emoji": "😱",
            "text": {"content": "WHAT?!", "color": "#3366FF"},
        },
        {
            "id": "07_sorry",
            "emotion": "Sorry / Apologize",
            "pose": "Deep bow with body bent forward, looking up with guilty eyes",
            "props": "Large sweat drop on head, wavy guilt lines around body",
            "emoji": "🙇",
            "text": {"content": "SORRY", "color": "#6688BB"},
        },
        {
            "id": "08_sleepy",
            "emotion": "Sleepy / Good Night",
            "pose": "Curled up in a ball, eyes peacefully closed, hugging bamboo plush",
            "props": "Three Zzz bubbles floating up, small crescent moon and stars",
            "emoji": "🌙",
            "text": {"content": "NIGHT~", "color": "#7766CC"},
        },
        {
            "id": "09_hungry",
            "emotion": "Hungry / Starving",
            "pose": "Sitting holding a bamboo stalk, mouth open ready to munch",
            "props": "Drool drop from mouth, sparkling eyes, rumbling belly effect",
            "emoji": "🤤",
            "text": {"content": "HUNGRY", "color": "#FF8833"},
        },
        {
            "id": "10_angry",
            "emotion": "Angry / Grumpy",
            "pose": "Sitting with puffed cheeks, arms crossed, eyebrows furrowed",
            "props": "Anger vein on forehead, small steam puffs from ears",
            "emoji": "😤",
            "text": {"content": "HMPH!", "color": "#DD4444"},
        },
        {
            "id": "11_cry",
            "emotion": "Sad / Crying",
            "pose": "Sitting on ground, paws covering eyes, tears streaming down",
            "props": "Waterfall tears from both eyes, puddle forming below",
            "emoji": "😭",
            "text": {"content": "NOOO", "color": "#4477DD"},
        },
        {
            "id": "12_yay",
            "emotion": "Excited / Celebrating",
            "pose": "Jumping with both paws raised high, huge grin, body bouncing",
            "props": "Sparkle effects, confetti pieces, speed lines showing energy",
            "emoji": "🎉",
            "text": {"content": "YAY!", "color": "#FFCC00"},
        },
        {
            "id": "13_please",
            "emotion": "Begging / Please",
            "pose": "Sitting with paws pressed together, big round watery puppy eyes",
            "props": "Sparkling watery eyes, slight head tilt, tiny sweat drop",
            "emoji": "🥺",
            "text": {"content": "PLEASE~", "color": "#CC77DD"},
        },
        {
            "id": "14_busy",
            "emotion": "Busy / Working",
            "pose": "Sitting at tiny laptop, paws typing rapidly, focused squinting eyes",
            "props": "Sweat drop on temple, speed lines near typing paws, determined expression",
            "emoji": "💻",
            "text": {"content": "BUSY", "color": "#5599CC"},
        },
        {
            "id": "15_omg",
            "emotion": "Amazed / OMG",
            "pose": "Standing with paws on cheeks, mouth in perfect O shape, body leaning back",
            "props": "Sparkle burst background, wide shimmering eyes, blush intensified",
            "emoji": "🤩",
            "text": {"content": "OMG!", "color": "#FF6600"},
        },
        {
            "id": "16_bye",
            "emotion": "Goodbye / See You",
            "pose": "Walking away, looking back over shoulder, one paw waving behind",
            "props": "Small smile, motion lines showing walking, tiny footprints below",
            "emoji": "👋",
            "text": {"content": "BYE~", "color": "#55BBAA"},
        },
    ],
    "platforms": [
        "line",
        "telegram",
    ],
}
