"""
Sticker Pack Configuration — Little Angel
==========================================
A cute, chibi angel character with blessings, prayers, and encouragement.
Soft pastel illustration style with fluffy wings and a tiny halo.

16 stickers with per-sticker text + colour configuration.
Text is composited in post-processing (Pillow), NOT generated by DALL-E.
"""

# =============================================================================
# CHARACTER DEFINITION
# =============================================================================
CHARACTER = {
    "name": "Little Angel",
    "species": "angel child",
    "body_color": "#FFF0E0",  # very light peach skin
    "blush_color": "#FFB6C1",  # light pink
    "outline_color": "#5C4033",  # warm brown
    "eye_style": "very large, round sparkly black eyes with tiny white highlight dots, extremely expressive",
    "accessory": "tiny golden halo floating above head, small fluffy white wings, simple white dress",
    "proportions": "chibi toddler, head is 60% of body, very round chubby cheeks, tiny stubby limbs",
    "body_description": (
        "adorable chibi angel child, very light peach skin, "
        "extremely large sparkly round eyes with white highlights, "
        "tiny button nose, big round chubby cheeks, "
        "soft fluffy white feathered wings (small, cute), "
        "tiny golden halo floating above head, "
        "simple white dress reaching knees, bare tiny feet, "
        "chibi toddler proportions, oversized head, stubby limbs, "
        "pink blush circles on cheeks"
    ),
    "features": [
        "chibi toddler proportions",
        "very light peach skin",
        "huge sparkly round eyes",
        "tiny golden halo",
        "small fluffy white wings",
        "simple white dress",
        "big round chubby cheeks",
        "pink blush circles",
        "bare tiny feet",
    ],
}

# =============================================================================
# ART STYLE — soft dreamy pastel
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "soft warm brown outlines, consistent 2-3px width",
    "coloring": "dreamy pastel colors, soft airbrushed shading, gentle light from above-right",
    "background": "clean solid white background with no other elements",
    "extras": (
        "kawaii sticker illustration style, cherubic innocent poses, "
        "soft glowing effects and sparkles, feather details, "
        "heavenly dreamy aesthetic with round fluffy shapes"
    ),
}

# =============================================================================
# TEXT DEFAULTS
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 80,
    "outline_width": 5,
    "outline_color": "#4A3728",
    "shadow_offset": [3, 4],
    "shadow_color": "#00000055",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Little Angel (16 stickers)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "little-angel",
    "pack_name": "Little Angel",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        {
            "id": "01_god_bless_you",
            "emotion": "Blessing / Loving",
            "pose": "Floating slightly above ground, both tiny hands raised outward in a blessing",
            "props": "Soft golden sparkles from hands, halo glowing brighter, gentle smile",
            "emoji": "🙏",
            "text": {"content": "GOD BLESS\nYOU", "color": "#DAA520"},
        },
        {
            "id": "02_praying_for_you",
            "emotion": "Devout / Caring",
            "pose": "Tiny hands clasped in prayer, head slightly bowed, wings folded gently",
            "props": "Small light rays above halo, serene closed eyes, feathers softly glowing",
            "emoji": "🙏",
            "text": {"content": "PRAYING\nFOR YOU", "color": "#6A5ACD"},
        },
        {
            "id": "03_have_faith",
            "emotion": "Encouraging / Bright",
            "pose": "One tiny hand on heart, other reaching forward, big determined eyes",
            "props": "Small star sparkle near hand, warm glow, determined sweet expression",
            "emoji": "✨",
            "text": {"content": "HAVE FAITH", "color": "#4682B4"},
        },
        {
            "id": "04_hallelujah",
            "emotion": "Ecstatic / Praising",
            "pose": "Both arms raised high, wings spread wide, head tilted back with huge smile",
            "props": "Bright beams from above, musical notes, golden sparkles everywhere",
            "emoji": "🎶",
            "text": {"content": "HALLELUJAH", "color": "#B8860B"},
        },
        {
            "id": "05_you_are_blessed",
            "emotion": "Affirming / Warm",
            "pose": "Floating and pointing gently at viewer, other hand on heart, sweet smile",
            "props": "Heart-shaped sparkle near pointing hand, warm angelic glow",
            "emoji": "🌈",
            "text": {"content": "YOU ARE\nBLESSED", "color": "#E75480"},
        },
        {
            "id": "06_god_is_good",
            "emotion": "Joyful / Celebrating",
            "pose": "Jumping with wings fluttering, tiny fists pumping the air, huge grin",
            "props": "Confetti sparkles, small feathers floating, radiating joy",
            "emoji": "🌟",
            "text": {"content": "GOD IS\nGOOD", "color": "#FF8C00"},
        },
        {
            "id": "07_amen",
            "emotion": "Reverent / Peaceful",
            "pose": "Hands clasped, eyes closed, tiny nod, wings gently folded",
            "props": "Soft halo glow intensified, peaceful golden aura, serene",
            "emoji": "🕊️",
            "text": {"content": "AMEN", "color": "#8B6914"},
        },
        {
            "id": "08_thank_you_lord",
            "emotion": "Grateful / Overjoyed",
            "pose": "Looking upward with both tiny arms raised, tears of joy, beaming smile",
            "props": "Warm light rays from above, golden sparkles, feathers catching light",
            "emoji": "💛",
            "text": {"content": "THANK YOU\nLORD", "color": "#CD853F"},
        },
        {
            "id": "09_i_love_you",
            "emotion": "Loving / Cuddly",
            "pose": "Hugging self with wings wrapped around like a cocoon, eyes closed happily",
            "props": "Pink hearts floating up, rosy cheeks extra bright, warm pink glow",
            "emoji": "❤️",
            "text": {"content": "I LOVE\nYOU", "color": "#DC143C"},
        },
        {
            "id": "10_trust_him",
            "emotion": "Reassuring / Calm",
            "pose": "Sitting on a small cloud, legs dangling, one hand resting on knee, soft smile",
            "props": "Fluffy cloud beneath, gentle breeze effect on hair, calm peaceful aura",
            "emoji": "☁️",
            "text": {"content": "TRUST HIM", "color": "#4169E1"},
        },
        {
            "id": "11_be_kind",
            "emotion": "Gentle / Sweet",
            "pose": "Kneeling to offer a small flower, sweet gentle expression, wings slightly open",
            "props": "Small daisy flower, heart-shaped petal, soft nature sparkles",
            "emoji": "🌸",
            "text": {"content": "BE KIND", "color": "#DB7093"},
        },
        {
            "id": "12_sending_love",
            "emotion": "Affectionate / Blowing kiss",
            "pose": "Blowing a kiss with one hand, other hand on hip, winking playfully",
            "props": "Heart-shaped kiss flying away, sparkle trail, playful expression",
            "emoji": "😘",
            "text": {"content": "SENDING\nLOVE", "color": "#FF69B4"},
        },
        {
            "id": "13_good_morning",
            "emotion": "Cheerful / Fresh",
            "pose": "Stretching with tiny arms up, wings stretching too, big yawn-to-smile",
            "props": "Small sun rising, morning sparkles, fresh awakening energy",
            "emoji": "🌅",
            "text": {"content": "GOOD\nMORNING", "color": "#FFA500"},
        },
        {
            "id": "14_good_night",
            "emotion": "Sleepy / Cozy",
            "pose": "Curled up on a cloud pillow, wings used as blanket, eyes drifting closed",
            "props": "Crescent moon, tiny stars, soft blue-purple glow, zzz floating up",
            "emoji": "🌙",
            "text": {"content": "GOOD\nNIGHT", "color": "#483D8B"},
        },
        {
            "id": "15_stay_strong",
            "emotion": "Brave / Supportive",
            "pose": "Standing with tiny fist raised, other hand on hip, determined cute expression",
            "props": "Small shield of light, star near fist, brave little stance",
            "emoji": "💪",
            "text": {"content": "STAY\nSTRONG", "color": "#B22222"},
        },
        {
            "id": "16_peace",
            "emotion": "Serene / Floating",
            "pose": "Floating peacefully with arms slightly open, eyes serenely closed",
            "props": "Soft white feathers drifting down, gentle breeze, dove nearby",
            "emoji": "🕊️",
            "text": {"content": "PEACE", "color": "#3CB371"},
        },
    ],
    "platforms": [
        "whatsapp",
        "telegram",
        "imessage_large",
        "print_etsy",
    ],
}
