"""
Sticker Pack Configuration — Chubby Mochi Hamster Vol.2: Study Mode
====================================================================
Same round, squishy hamster — now hitting the books!
Painted illustration style with thick outlines and bold text overlays.

16 learning/study-themed stickers with per-sticker text + colour config.
Text is composited in post-processing (Pillow), NOT generated by SDXL.

Vol.1 concepts (AVOID): HELLO, THANK YOU, SORRY, OK, WHAT?!, LOL,
LOVE YOU, GOOD NIGHT, HUNGRY, BUSY, WAITING, NOOO, YES, PLEASE
"""

# =============================================================================
# CHARACTER DEFINITION  (identical to Vol.1)
# =============================================================================
CHARACTER = {
    "name": "Mochi Hamster",
    "species": "round hamster",
    "body_color": "#E8A84C",  # warm orange-brown
    "blush_color": "#FF9999",  # soft pink
    "outline_color": "#333333",  # dark charcoal
    "eye_style": "large shiny black round eyes, expressive, with tiny white highlight dots",
    "accessory": None,
    "proportions": "chibi, extremely round body like a ball, tiny stubby legs, head is 55% of body height",
    # --- v2 fields ---
    "body_description": (
        "cute round chubby hamster, warm orange-brown fur, "
        "white belly patch, large shiny black round eyes, "
        "tiny highlight dots in eyes, small pink nose, "
        "large round ears, extremely round ball-shaped body, "
        "puffed cheek pouches, tiny stubby paws, "
        "pink blush marks on cheeks"
    ),
    "features": [
        "round chubby body",
        "warm orange-brown fur",
        "white belly patch",
        "puffed cheek pouches",
        "large round ears",
        "shiny black eyes with highlights",
        "tiny stubby paws",
        "pink blush cheeks",
    ],
}

# =============================================================================
# ART STYLE  (identical to Vol.1)
# =============================================================================
STYLE = {
    "art_style": "painted_illustration",
    "outline_type": "thick black outlines, consistent 3-4px width",
    "coloring": "semi-realistic painting style, soft painterly shading, warm color palette",
    "background": "clean solid white background with no other elements",
    "extras": (
        "sticker illustration style, dynamic expressive poses, "
        "action effects like motion lines and sweat drops, "
        "kawaii aesthetic with exaggerated proportions"
    ),
}

# =============================================================================
# TEXT DEFAULTS  (identical to Vol.1)
# =============================================================================
TEXT_DEFAULTS = {
    "font": "FredokaOne-Regular.ttf",
    "font_size": 85,
    "outline_width": 6,
    "outline_color": "#1a1a1a",
    "shadow_offset": [4, 5],
    "shadow_color": "#00000099",
    "position": "top-center",
    "padding_top": 25,
}

# =============================================================================
# PACK: Chubby Mochi Hamster Vol.2 — Study Mode (16 stickers)
# =============================================================================
PACK_CONFIG = {
    "pack_id": "chubby-mochi-hamster-2",
    "pack_name": "Chubby Mochi Hamster Vol.2: Study Mode",
    "publisher": "BobaStickers",
    "character": CHARACTER,
    "style": STYLE,
    "text_defaults": TEXT_DEFAULTS,
    "stickers": [
        # ------------------------------------------------------------------
        # 1 — Studying hard
        # ------------------------------------------------------------------
        {
            "id": "01_studying",
            "emotion": "Focused / Studying",
            "pose": "Sitting at a tiny desk, paws holding a pencil, leaning over an open book",
            "props": "Stack of books beside desk, focused squinting eyes, small reading glasses on nose",
            "emoji": "📖",
            "text": {"content": "STUDYING", "color": "#5588CC"},
        },
        # ------------------------------------------------------------------
        # 2 — Brain overload
        # ------------------------------------------------------------------
        {
            "id": "02_brain_full",
            "emotion": "Overwhelmed / Brain Full",
            "pose": "Sitting with paws on head, eyes spiral-dazed, cheeks puffed to max",
            "props": "Steam coming out of ears, math symbols and letters floating around head, dizzy swirls",
            "emoji": "🤯",
            "text": {"content": "BRAIN FULL", "color": "#FF5566"},
        },
        # ------------------------------------------------------------------
        # 3 — Eureka / Got it!
        # ------------------------------------------------------------------
        {
            "id": "03_eureka",
            "emotion": "Excited discovery / Eureka",
            "pose": "Jumping up with one paw raised high pointing up, wide eyes, huge grin",
            "props": "Bright lightbulb glowing above head, sparkle effects, energy lines radiating outward",
            "emoji": "💡",
            "text": {"content": "GOT IT!", "color": "#FFCC00"},
        },
        # ------------------------------------------------------------------
        # 4 — Let's go / Motivated
        # ------------------------------------------------------------------
        {
            "id": "04_lets_go",
            "emotion": "Motivated / Pumped up",
            "pose": "Standing with both paws clenched in fists, powerful stance, determined eyes",
            "props": "Fire aura around body, intense focused expression, motion lines showing power",
            "emoji": "🔥",
            "text": {"content": "LET'S GO!", "color": "#FF6600"},
        },
        # ------------------------------------------------------------------
        # 5 — Need coffee
        # ------------------------------------------------------------------
        {
            "id": "05_need_coffee",
            "emotion": "Tired / Need caffeine",
            "pose": "Slouching forward, half-closed droopy eyes, both paws wrapped around a big coffee mug",
            "props": "Steam rising from coffee mug, dark under-eye circles, messy fur on head",
            "emoji": "☕",
            "text": {"content": "NEED COFFEE", "color": "#8B5E3C"},
        },
        # ------------------------------------------------------------------
        # 6 — Quiz time / Test
        # ------------------------------------------------------------------
        {
            "id": "06_quiz_time",
            "emotion": "Nervous excitement / Alert",
            "pose": "Sitting upright at attention, paws gripping pencil tightly, wide alert eyes",
            "props": "Paper with checkboxes on desk, sweat drop on temple, trembling motion lines",
            "emoji": "✏️",
            "text": {"content": "QUIZ TIME", "color": "#3399EE"},
        },
        # ------------------------------------------------------------------
        # 7 — Aced it / Perfect score
        # ------------------------------------------------------------------
        {
            "id": "07_aced_it",
            "emotion": "Proud / Triumphant",
            "pose": "Standing tall holding up a paper with A+ grade, chest puffed out, huge proud grin",
            "props": "Sparkles and stars around the paper, golden glow effect, confetti pieces",
            "emoji": "💯",
            "text": {"content": "ACED IT!", "color": "#FFD700"},
        },
        # ------------------------------------------------------------------
        # 8 — Help me / Confused
        # ------------------------------------------------------------------
        {
            "id": "08_help_me",
            "emotion": "Confused / Lost",
            "pose": "Sitting surrounded by open books, paws tangled in hair, tilted head",
            "props": "Multiple question marks floating above, tangled scribble lines, bewildered wide eyes",
            "emoji": "❓",
            "text": {"content": "HELP ME", "color": "#AA55CC"},
        },
        # ------------------------------------------------------------------
        # 9 — Break time
        # ------------------------------------------------------------------
        {
            "id": "09_break_time",
            "emotion": "Relieved / Relaxing",
            "pose": "Leaning back in chair with paws behind head, eyes closed, satisfied smile",
            "props": "Clock showing break time, snack on desk, relaxation waves around body",
            "emoji": "😌",
            "text": {"content": "BREAK TIME", "color": "#44BB88"},
        },
        # ------------------------------------------------------------------
        # 10 — Due tomorrow / Panic
        # ------------------------------------------------------------------
        {
            "id": "10_due_tomorrow",
            "emotion": "Panic / Dread",
            "pose": "Eyes popping out, paws on cheeks in horror pose, body stiff and trembling",
            "props": "Calendar page showing deadline, alarm bells ringing, lightning bolt shock lines",
            "emoji": "😨",
            "text": {"content": "DUE TOMORROW", "color": "#DD3344"},
        },
        # ------------------------------------------------------------------
        # 11 — Good luck
        # ------------------------------------------------------------------
        {
            "id": "11_good_luck",
            "emotion": "Encouraging / Supportive",
            "pose": "Both paws giving double thumbs up, warm cheerful smile, slight forward lean",
            "props": "Four-leaf clover floating nearby, sparkle effects, warm golden glow",
            "emoji": "🍀",
            "text": {"content": "GOOD LUCK", "color": "#33AA55"},
        },
        # ------------------------------------------------------------------
        # 12 — So tired / Dead
        # ------------------------------------------------------------------
        {
            "id": "12_so_tired",
            "emotion": "Exhausted / Dead tired",
            "pose": "Face-planted flat on open book, body completely limp and deflated",
            "props": "Soul floating out of body as tiny ghost, X eyes, open book as pillow",
            "emoji": "😵",
            "text": {"content": "SO TIRED", "color": "#7788AA"},
        },
        # ------------------------------------------------------------------
        # 13 — You can do it / Cheer
        # ------------------------------------------------------------------
        {
            "id": "13_you_can_do_it",
            "emotion": "Cheerful encouragement",
            "pose": "Holding tiny pom-poms, jumping mid-air with legs apart, big open mouth cheer",
            "props": "Star burst effect behind, exclamation marks, energetic motion lines",
            "emoji": "📣",
            "text": {"content": "YOU GOT THIS!", "color": "#FF8800"},
        },
        # ------------------------------------------------------------------
        # 14 — Procrastinating
        # ------------------------------------------------------------------
        {
            "id": "14_procrastinating",
            "emotion": "Guilty / Distracted",
            "pose": "Lying on belly scrolling a tiny phone, open textbook ignored beside",
            "props": "Thought bubble showing phone screen, half-lidded relaxed eyes, books gathering dust",
            "emoji": "📱",
            "text": {"content": "LATER...", "color": "#BB88CC"},
        },
        # ------------------------------------------------------------------
        # 15 — Group study
        # ------------------------------------------------------------------
        {
            "id": "15_group_study",
            "emotion": "Friendly / Social",
            "pose": "Waving one paw invitingly, other paw pointing to an empty chair beside",
            "props": "Small table with books, extra chair, welcoming warm smile",
            "emoji": "👥",
            "text": {"content": "STUDY WITH ME", "color": "#5599BB"},
        },
        # ------------------------------------------------------------------
        # 16 — All done / Finished
        # ------------------------------------------------------------------
        {
            "id": "16_all_done",
            "emotion": "Relieved / Accomplished",
            "pose": "Both paws thrown up in celebration, eyes closed with huge relieved smile",
            "props": "Completed checklist floating nearby, sparkle burst, weight lifted effect lines",
            "emoji": "✅",
            "text": {"content": "ALL DONE!", "color": "#22BB66"},
        },
    ],
    "platforms": [
        "whatsapp",
        "telegram",
        "line",
        "imessage_large",
    ],
}
