"""
Pack Configuration for My Pack
Generated by setup_pack.py
"""

CHARACTER = {
    "name": "Character",
    "species": "animal",
    "body_color": "#FFB6C1",  # TODO: Change to actual color
    "blush_color": "#FF69B4",
    "outline_color": "#333333",
    "eye_style": "simple black oval eyes, no pupils, highly expressive",
    "accessory": "TODO: Define accessory",
    "proportions": "chibi, head is 60% of total body height, stubby short limbs",
    "body_description": (
        f"cute {species} named Character, TODO: add description"
    ),
    "features": [
        "TODO: feature 1",
        "TODO: feature 2",
        "TODO: feature 3",
    ],
}

STYLE = {
    "outline_type": "thick uniform outline, consistent 3-4px width",
    "coloring": "flat colors only, absolutely no gradients, no realistic shading",
    "background": "clean solid white background with no other elements",
    "extras": (
        "die-cut sticker style with a thick white outline border "
        "around the ENTIRE character"
    ),
    "art_style": "flat_vector",  # or "painted_illustration"
}

PACK_CONFIG = {
    "pack_id": "my-pack",
    "pack_name": "My Pack",
    "publisher": "FHStudio",
    "character": CHARACTER,
    "style": STYLE,
    "platforms": ["line", "whatsapp", "telegram", "imessage", "print"],
    "stickers": [
        {
            "id": "01_happy",
            "emotion": "Happy",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "😊",
            "animation": {"type": "bounce", "duration_ms": 2000},
        },
        {
            "id": "02_love",
            "emotion": "In Love",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "❤️",
            "animation": {"type": "bounce", "duration_ms": 2000},
        },
        {
            "id": "03_sad",
            "emotion": "Sad",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "😢",
            "animation": {"type": "bounce", "duration_ms": 2000},
        },
        {
            "id": "04_angry",
            "emotion": "Angry",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "😠",
            "animation": {"type": "bounce", "duration_ms": 2000},
        },
        {
            "id": "05_sleepy",
            "emotion": "Sleepy",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "😴",
            "animation": {"type": "bounce", "duration_ms": 2000},
        },
        {
            "id": "06_excited",
            "emotion": "Excited",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "😮",
            "animation": {"type": "bounce", "duration_ms": 2000},
        },
        {
            "id": "07_laughing",
            "emotion": "Laughing",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "😂",
            "animation": {"type": "bounce", "duration_ms": 2000},
        },
        {
            "id": "08_thinking",
            "emotion": "Thinking",
            "pose": "TODO: Define pose",
            "props": "TODO: Define props",
            "emoji": "🤔",
            "animation": {"type": "bounce", "duration_ms": 2000},
        }
    ],
}
